<?php

/**
 * this file is automatically generated. use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'dzcoinfbcodelintengine' => 'lint_engine/dzcoinfbcodelintengine.php',
    'fbcodecpplinter' => 'cpp_linter/fbcodecpplinter.php',
    'pfffcpplinter' => 'cpp_linter/pfffcpplinter.php',
    'arcanistcpplintlinter' => 'cpp_linter/arcanistcpplintlinter.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'dzcoinfbcodelintengine' => 'arcanistlintengine',
    'fbcodecpplinter' => 'arcanistlinter',
    'pfffcpplinter' => 'arcanistlinter',
  ),
));


